/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticates a user and issues an opaque server-side session token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the active session token.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Returns the profile and granted permissions of the authenticated user.
         */
        get: operations["get_current_user_profile_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Target
         * @description Analyze a filesystem target without mutation (read-only, requires evidence.hash permission).
         */
        post: operations["analyze_target_api_targets_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Target
         * @description Retrieve an analyzed target by its ID (requires case.view permission).
         */
        get: operations["get_target_api_targets__target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Operations
         * @description List persisted operations (requires ``operation.view``).
         *
         *     This closes the gap that forced an operator to paste an operation ID into
         *     the address bar: the console had a ledger and the contract published no way
         *     to fill it.
         *
         *     Filtering is applied in the database, and every field returned comes from a
         *     persisted row. Nothing is synthesised - no identifier, no state, no
         *     progress. An operation that does not exist does not appear.
         *
         *     Authorization is the existing model, unchanged: ``operation.view`` is held
         *     by ADMIN, INVESTIGATOR, OPERATOR, AUDITOR and VIEWER, and this route exposes
         *     only operation records. It is not a general database listing, and it exposes
         *     no audit, evidence or certificate material - those keep their own
         *     permissions (``audit.view``, ``evidence.view``).
         *
         *     An unrecognised ``state`` is refused rather than ignored: a filter silently
         *     dropped returns more than was asked for while looking like it returned
         *     exactly what was asked for.
         */
        get: operations["list_operations_api_operations_get"];
        put?: never;
        /**
         * Create Operation
         * @description Creates an erasure operation in PENDING_APPROVAL state.
         *     Does NOT execute destructive deletion upon creation (Approval-gated lifecycle).
         */
        post: operations["create_operation_api_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Operation
         * @description Approves a pending operation subject to Separation of Duties enforcement.
         *     Requires ADMIN role / operation.approve permission.
         */
        post: operations["approve_operation_api_operations__operation_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Operation Endpoint
         * @description Executes an approved operation.
         *     Requires OPERATOR role / operation.execute permission.
         *     Enforces that operation was approved prior to execution.
         */
        post: operations["execute_operation_endpoint_api_operations__operation_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation
         * @description Get operation status and details (requires operation.view permission).
         */
        get: operations["get_operation_api_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Operation
         * @description Request operation cancellation (requires operation.request permission).
         */
        post: operations["cancel_operation_api_operations__operation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation Events
         * @description Retrieve audit and lifecycle events for an operation (requires operation.view permission).
         */
        get: operations["get_operation_events_api_operations__operation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Pipeline
         * @description Run an approved operation through the full closed loop.
         *
         *     Requires ``operation.execute``. Holding that permission is necessary but not
         *     sufficient: the pipeline's own AUTHORIZE stage additionally requires a
         *     durable approval recorded by someone other than the requester, so a single
         *     actor cannot both request and run a destructive operation.
         *
         *     A 200 does not mean the target was erased. It means the pipeline ran and
         *     reported what happened - which may be a refusal. Read ``final_state`` and the
         *     per-stage statuses.
         */
        post: operations["run_pipeline_api_operations__operation_id__pipeline_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery-objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recovery Objects
         * @description List sealed recovery objects metadata (requires recovery.view permission, no secret leakage).
         */
        get: operations["list_recovery_objects_api_recovery_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery-objects/{recovery_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Recovery Object
         * @description Restore a controlled-recoverable object to a validated destination.
         *     Requires authenticated user with recovery.execute permission.
         *     Rejects existing destination files by default unless allow_overwrite=True.
         */
        post: operations["restore_recovery_object_api_recovery_objects__recovery_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Certificate
         * @description Retrieve an issued certificate (requires evidence.view).
         *
         *     Returns the signer's public key only; no private key exists in this API.
         */
        get: operations["get_certificate_api_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Certificate Endpoint
         * @description Verify a certificate across ten independent dimensions.
         *
         *     The caller may supply the operation and target it *expects* this certificate
         *     to attest to. It cannot supply the outcome: signer trust comes from the
         *     server's TrustStore, and evidence integrity is recomputed from the stored
         *     evidence. A request that supplies no expectations gets ``INCONCLUSIVE``,
         *     which is the truthful answer when nothing independent was available to check
         *     against.
         */
        post: operations["verify_certificate_endpoint_api_certificates__certificate_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Evidence Endpoint
         * @description Verify raw evidence package signature against Ed25519 public key (requires evidence.verify permission).
         */
        post: operations["verify_evidence_endpoint_api_evidence_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Events
         * @description Read audit records, oldest first (requires ``audit.view``).
         *
         *     Unrecognised filter values are rejected with 422 rather than ignored. A
         *     filter that is silently dropped returns *more* than was asked for while
         *     looking like it returned exactly what was asked for - in an audit context,
         *     a way to miss the record you were told to find.
         */
        get: operations["list_audit_events_api_audit_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Audit Chain Endpoint
         * @description Verify the persisted audit chain (requires ``audit.verify``).
         *
         *     Records are loaded from storage and rehashed. The caller supplies no
         *     digests, no records and no expected outcome - there is no field in this
         *     request in which to assert that the log is intact, which is what keeps the
         *     answer the server's rather than the caller's.
         */
        post: operations["verify_audit_chain_endpoint_api_audit_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssuranceStatusOut
         * @enum {string}
         */
        AssuranceStatusOut: "PASSED" | "PARTIAL" | "INCONCLUSIVE" | "FAILED";
        /**
         * AuditChainVerificationOut
         * @description The result of verifying the persisted audit chain.
         */
        AuditChainVerificationOut: {
            /** Status */
            status: string;
            /** Checked */
            checked: number;
            /** Reason */
            reason: string;
            /** Links */
            links: components["schemas"]["AuditLinkOut"][];
            /** First Invalid Audit Id */
            first_invalid_audit_id?: string | null;
            /**
             * Records Predating Chain
             * @default 0
             */
            records_predating_chain: number;
            /** Proves */
            proves: string[];
            /** Does Not Prove */
            does_not_prove: string[];
            /**
             * Scope Note
             * @default This result describes the integrity of the audit log only. It is not a statement about evidence integrity, erasure success, or certificate trust, each of which is verified separately against its own artefact.
             */
            scope_note: string;
        };
        /**
         * AuditEventOut
         * @description One audit record as published.
         */
        AuditEventOut: {
            /** Audit Id */
            audit_id: string;
            /** Sequence */
            sequence: number;
            /** Event Type */
            event_type: string;
            /** Outcome */
            outcome: string;
            /** Actor Id */
            actor_id: string;
            /** Actor Role */
            actor_role: string;
            /** Actor Source */
            actor_source: string;
            /** Operation Id */
            operation_id?: string | null;
            /** Target Identity */
            target_identity?: string | null;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Certificate Id */
            certificate_id?: string | null;
            /**
             * Summary
             * @default
             */
            summary: string;
            /** Safe Metadata */
            safe_metadata?: {
                [key: string]: unknown;
            };
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Digest */
            digest: string;
            /** Previous Audit Id */
            previous_audit_id?: string | null;
            /** Previous Audit Digest */
            previous_audit_digest?: string | null;
        };
        /**
         * AuditEventPageOut
         * @description A page of audit records, oldest first.
         *
         *     ``total_records`` is the height of the whole log, not the size of this
         *     page, so a reader can tell a page is a window without inferring it from the
         *     page happening to be full.
         */
        AuditEventPageOut: {
            /** Events */
            events: components["schemas"]["AuditEventOut"][];
            /** Returned */
            returned: number;
            /** Total Records */
            total_records: number;
            /**
             * Records Predating Chain
             * @default 0
             */
            records_predating_chain: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** AuditLinkOut */
        AuditLinkOut: {
            /** Audit Id */
            audit_id: string;
            /** Sequence */
            sequence: number;
            /** Status */
            status: string;
            /** Detail */
            detail: string;
        };
        /**
         * AuditVerifyRequest
         * @description Optional narrowing for a verification request.
         *
         *     Supplying ``operation_id`` narrows which records are examined. It cannot
         *     make a window look complete: a subset that does not begin at the genesis
         *     record is reported ``UNVERIFIABLE``, because the chain spans every event in
         *     the system and a per-operation slice necessarily has history before it.
         */
        AuditVerifyRequest: {
            /** Operation Id */
            operation_id?: string | null;
        };
        /** CertificateOut */
        CertificateOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /** Evidence Id */
            evidence_id?: string | null;
            /** Evidence Digest */
            evidence_digest: string;
            /** Certificate Version */
            certificate_version: string;
            /** Canonicalization Version */
            canonicalization_version?: string | null;
            /** Evidence Schema Version */
            evidence_schema_version?: string | null;
            /** Target Identity */
            target_identity?: string | null;
            /** Method */
            method?: string | null;
            /** Result */
            result?: string | null;
            /** Signer Id */
            signer_id?: string | null;
            /** Signing Algorithm */
            signing_algorithm: string;
            /** Key Id */
            key_id?: string | null;
            /** Public Key */
            public_key: string;
            /** Signature */
            signature: string;
            /** Claim */
            claim?: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
            /** Limitations */
            limitations?: string[];
        };
        /** CertificateVerificationOut */
        CertificateVerificationOut: {
            /** Certificate Id */
            certificate_id: string;
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "VALID" | "INVALID" | "INCONCLUSIVE";
            /**
             * Dimensions
             * @description Exactly one result per verification dimension. A PASS on SIGNATURE_VALIDITY does not imply overall certificate validity: only overall_status does. NOT_CHECKED and INCONCLUSIVE are honest absences of evidence and must not be rendered as success.
             */
            dimensions: components["schemas"]["DimensionResultOut"][];
            /** Cannot Prove */
            cannot_prove?: string[];
            /** Certificate Version */
            certificate_version?: string | null;
            /** Verifier Version */
            verifier_version: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /** Signature Valid */
            signature_valid?: boolean | null;
            /** Evidence Integrity */
            evidence_integrity?: boolean | null;
            /** Signer Trusted */
            signer_trusted?: boolean | null;
        };
        /**
         * CertificateVerificationRequest
         * @description Independent expectations the caller brings to the verification.
         *
         *     Both are optional. Omitting one is honest - the corresponding dimension
         *     reports ``NOT_CHECKED`` and the overall result becomes ``INCONCLUSIVE``
         *     rather than pretending the check succeeded.
         */
        CertificateVerificationRequest: {
            /**
             * Expected Operation Id
             * @description The operation the caller believes this certificate attests to. Compared against the certificate and its evidence.
             */
            expected_operation_id?: string | null;
            /**
             * Expected Target Identity
             * @description The target the caller believes this certificate attests to. Compared against the certificate and its evidence.
             */
            expected_target_identity?: string | null;
        };
        /** ConfirmationInput */
        ConfirmationInput: {
            /**
             * Acknowledged Risk
             * @description Must explicitly acknowledge destructive operation risk
             */
            acknowledged_risk: boolean;
        };
        /**
         * CoverageOut
         * @description What was actually searched.
         *
         *     Present so no client ever has to infer coverage from an empty findings list
         *     or a single boolean.
         */
        CoverageOut: {
            /** @default NOT_PERFORMED */
            residual_analysis: components["schemas"]["CoverageState"];
            /** @default NOT_PERFORMED */
            recovery_test: components["schemas"]["CoverageState"];
            recovery_methods?: components["schemas"]["RecoveryMethodCoverageOut"];
            residual_scanners?: components["schemas"]["ResidualScannerCoverageOut"];
        };
        /**
         * CoverageState
         * @description How much of a supported analysis actually ran.
         *
         *     The distinction between `PARTIAL` and `PERFORMED` is the point: before it
         *     existed, "one of several recovery methods ran" and "every supported method
         *     ran" were reported identically, and a client could not tell them apart.
         * @enum {string}
         */
        CoverageState: "NOT_PERFORMED" | "UNAVAILABLE" | "INCONCLUSIVE" | "PARTIAL" | "PERFORMED";
        /** CreateOperationRequest */
        CreateOperationRequest: {
            /** Target Id */
            target_id: string;
            /** Mode */
            mode: string;
            /**
             * Policy Id
             * @description Must be an allowlisted backend policy. Currently registered: ERASURE.LOGICAL.SELECTIVE.V1, ERASURE.LOGICAL.TREE.V1, ERASURE.RECOVERABLE.ENCRYPTED.V1. The backend rejects any other identifier; the frontend must not invent policy identifiers.
             * @default ERASURE.LOGICAL.SELECTIVE.V1
             */
            policy_id: string;
            confirmation: components["schemas"]["ConfirmationInput"];
            recovery?: components["schemas"]["RecoveryConfig"] | null;
        };
        /** DimensionResultOut */
        DimensionResultOut: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "STRUCTURE" | "VERSION_COMPATIBILITY" | "EVIDENCE_AVAILABILITY" | "EVIDENCE_DIGEST" | "SIGNATURE_VALIDITY" | "PUBLIC_KEY_CONSISTENCY" | "SIGNER_TRUST" | "EVIDENCE_CHAIN_INTEGRITY" | "OPERATION_CONSISTENCY" | "TARGET_CONSISTENCY";
            /**
             * Result
             * @enum {string}
             */
            result: "PASS" | "FAIL" | "NOT_CHECKED" | "INCONCLUSIVE";
            /** Detail */
            detail: string;
            /** Evidence Ref */
            evidence_ref?: string | null;
        };
        /** EvidenceVerificationRequest */
        EvidenceVerificationRequest: {
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Signature */
            signature: string;
            /** Public Key */
            public_key: string;
        };
        /** EvidenceVerificationResult */
        EvidenceVerificationResult: {
            /** Valid */
            valid: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Status
             * @default COMPLETED
             */
            status: string;
            /**
             * Message
             * @default Session successfully terminated
             */
            message: string;
        };
        /** OperationEventOut */
        OperationEventOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /** Sequence */
            sequence: number;
            /** Event Type */
            event_type: string;
            /** From State */
            from_state?: string | null;
            /** To State */
            to_state?: string | null;
            /** Payload */
            payload?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OperationOut */
        OperationOut: {
            /** Id */
            id: string;
            /** Target Id */
            target_id: string;
            /** Mode */
            mode: string;
            /**
             * State
             * @description Operation lifecycle state. Authoritative values: CREATED, ANALYZING, PENDING_APPROVAL, READY, ERASING, VERIFYING, RECOVERY_TEST, RESIDUAL_SCAN, RESIDUAL_ANALYSIS, ASSESSING, CERTIFYING, RECONCILIATION_REQUIRED, COMPLETED, PARTIAL, FAILED, INCONCLUSIVE, CANCELLED. Terminal states: COMPLETED, PARTIAL, FAILED, INCONCLUSIVE, CANCELLED. Consumers must render PARTIAL and INCONCLUSIVE as distinct outcomes and must never collapse them into success.
             */
            state: string;
            /** Policy Id */
            policy_id?: string | null;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /** Warnings */
            warnings?: string[];
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * OperationPageOut
         * @description A page of persisted operations, newest first.
         *
         *     ``total`` is the number of operations matching the filter, not the size of
         *     this page, so a reader can tell a window from the whole set without
         *     inferring it from the page happening to be full.
         *
         *     Every row comes from the database. No identifier and no state is
         *     synthesised here; an operation that does not exist simply does not appear.
         */
        OperationPageOut: {
            /** Operations */
            operations: components["schemas"]["OperationOut"][];
            /** Returned */
            returned: number;
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * OperationStateOut
         * @description Terminal states an operation can end the pipeline in.
         * @enum {string}
         */
        OperationStateOut: "COMPLETED" | "PARTIAL" | "FAILED" | "INCONCLUSIVE" | "CANCELLED";
        /**
         * PipelineResultOut
         * @description The whole run.
         *
         *     ``certificate_id`` is null whenever issuance was refused or unavailable, and
         *     the corresponding stage says why. A null certificate is a normal, meaningful
         *     outcome - it means nothing certifiable was established - and callers must not
         *     treat it as an error.
         */
        PipelineResultOut: {
            /** Operation Id */
            operation_id: string;
            /** Target Identity */
            target_identity: string;
            final_state: components["schemas"]["OperationStateOut"];
            /** Stages */
            stages: components["schemas"]["PipelineStageOut"][];
            /** Evidence Id */
            evidence_id?: string | null;
            /** Evidence Digest */
            evidence_digest?: string | null;
            /** Certificate Id */
            certificate_id?: string | null;
            assurance_status?: components["schemas"]["AssuranceStatusOut"] | null;
            verification_status?: components["schemas"]["VerificationStatusOut"] | null;
            /** @description What was actually searched. Read this alongside `assurance_status`: PASSED with PARTIAL recovery coverage means no artifacts were found by the methods that ran, not that every method was tried. */
            coverage?: components["schemas"]["CoverageOut"];
            /**
             * Limitations
             * @description What this operation did not establish, including recovery methods that were never attempted and sanitization that was never performed.
             */
            limitations?: string[];
            /**
             * Privilege Isolated
             * @default false
             */
            privilege_isolated: boolean;
        };
        /**
         * PipelineStage
         * @description The closed loop, in order. Mirrors ``core.pipeline.Stage``.
         * @enum {string}
         */
        PipelineStage: "DISCOVER" | "BASELINE" | "RECOMMEND" | "AUTHORIZE" | "ERASE" | "VALIDATE" | "TEST_RECOVERY" | "ANALYZE_RESIDUALS" | "ASSESS_ASSURANCE" | "GENERATE_EVIDENCE" | "ISSUE_CERTIFICATE" | "VERIFY_CERTIFICATE";
        /**
         * PipelineStageOut
         * @description One stage, and what it established.
         */
        PipelineStageOut: {
            stage: components["schemas"]["PipelineStage"];
            status: components["schemas"]["PipelineStageStatus"];
            /**
             * Detail
             * @description Why the stage ended as it did. Human-readable; never the only machine-readable signal - use `status`.
             */
            detail: string;
        };
        /**
         * PipelineStageStatus
         * @description How a stage ended.
         *
         *     ``SKIPPED`` and ``UNAVAILABLE`` are distinct on the wire for the same reason
         *     they are distinct internally: chosen not to run, versus tried and could not.
         * @enum {string}
         */
        PipelineStageStatus: "COMPLETED" | "REFUSED" | "FAILED" | "UNAVAILABLE" | "SKIPPED";
        /** RecoveryConfig */
        RecoveryConfig: {
            /**
             * Retention Seconds
             * @default 86400
             */
            retention_seconds: number | null;
        };
        /**
         * RecoveryMethodCoverageOut
         * @description Which recovery methods ran, and what each one did.
         *
         *     Named lists rather than counts, so a client can render exactly which
         *     techniques were and were not applied instead of inferring it.
         */
        RecoveryMethodCoverageOut: {
            /**
             * Supported
             * @description Methods this build can perform at all.
             */
            supported?: string[];
            /** Attempted */
            attempted?: string[];
            /**
             * Successful
             * @description Methods that recovered the data. Non-empty means recoverable.
             */
            successful?: string[];
            /**
             * Failed
             * @description Methods that ran and did not recover the data. Evidence about those methods only - never evidence of irrecoverability.
             */
            failed?: string[];
            /**
             * Unavailable
             * @description Methods never attempted, because this build cannot perform them.
             */
            unavailable?: string[];
        };
        /** RecoveryObjectOut */
        RecoveryObjectOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /**
             * Status
             * @default SEALED
             */
            status: string;
            /** Original Sha256 */
            original_sha256: string;
            /** Original Size */
            original_size?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /**
         * ResidualScannerCoverageOut
         * @description Which residual scanners ran.
         */
        ResidualScannerCoverageOut: {
            /** Supported */
            supported?: string[];
            /** Ran */
            ran?: string[];
            /** Inconclusive */
            inconclusive?: string[];
            /** Unavailable */
            unavailable?: string[];
        };
        /** RestoreRequest */
        RestoreRequest: {
            /** Destination */
            destination: string;
            /**
             * Allow Overwrite
             * @description Explicit consent flag required to overwrite an existing destination file
             * @default false
             */
            allow_overwrite: boolean;
        };
        /** RestoreResponse */
        RestoreResponse: {
            /** Status */
            status: string;
            /** Destination */
            destination: string;
            /** Sha256 */
            sha256: string;
            /** Integrity Verified */
            integrity_verified: boolean;
        };
        /**
         * TargetAnalyzeRequest
         * @description Request to analyze a target.
         */
        TargetAnalyzeRequest: {
            /** Path */
            path: string;
            /**
             * Include Content Analysis
             * @default false
             */
            include_content_analysis: boolean;
        };
        /** TargetOut */
        TargetOut: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Canonical Path */
            canonical_path: string;
            /** Target Type */
            target_type: string;
            /** File Count */
            file_count?: number | null;
            /** Total Size */
            total_size?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
        };
        /**
         * TargetProfile
         * @description Profile of analyzed target.
         */
        TargetProfile: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Canonical Path */
            canonical_path?: string | null;
            /** Type */
            type: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Sha256 */
            sha256?: string | null;
            /** Storage Profile */
            storage_profile?: {
                [key: string]: unknown;
            };
            /** Sensitivity */
            sensitivity?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: string[];
            /** Errors */
            errors?: string[];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Roles */
            roles?: string[];
            /** Permissions */
            permissions?: string[];
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Authenticated At */
            last_authenticated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VerificationStatusOut
         * @enum {string}
         */
        VerificationStatusOut: "VALID" | "INVALID" | "INCONCLUSIVE" | "ERROR";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_target_api_targets_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_target_api_targets__target_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_operations_api_operations_get: {
        parameters: {
            query?: {
                state?: string | null;
                operation_id?: string | null;
                requested_by?: string | null;
                target_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_operation_api_operations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_operation_api_operations__operation_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_operation_endpoint_api_operations__operation_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_api_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_operation_api_operations__operation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_events_api_operations__operation_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_pipeline_api_operations__operation_id__pipeline_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PipelineResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recovery_objects_api_recovery_objects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_recovery_object_api_recovery_objects__recovery_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                recovery_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_certificate_api_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificate_endpoint_api_certificates__certificate_id__verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CertificateVerificationRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateVerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_evidence_endpoint_api_evidence_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceVerificationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_events_api_audit_events_get: {
        parameters: {
            query?: {
                operation_id?: string | null;
                actor_id?: string | null;
                event_type?: string | null;
                outcome?: string | null;
                since?: string | null;
                until?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_audit_chain_endpoint_api_audit_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AuditVerifyRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditChainVerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
