/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticates a user and issues an opaque server-side session token.
         */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the active session token.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Profile
         * @description Returns the profile and granted permissions of the authenticated user.
         */
        get: operations["get_current_user_profile_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Target
         * @description Analyze a filesystem target without mutation (read-only, requires evidence.hash permission).
         */
        post: operations["analyze_target_api_targets_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/targets/{target_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Target
         * @description Retrieve an analyzed target by its ID (requires case.view permission).
         */
        get: operations["get_target_api_targets__target_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Operation
         * @description Creates an erasure operation in PENDING_APPROVAL state.
         *     Does NOT execute destructive deletion upon creation (Approval-gated lifecycle).
         */
        post: operations["create_operation_api_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Operation
         * @description Approves a pending operation subject to Separation of Duties enforcement.
         *     Requires ADMIN role / operation.approve permission.
         */
        post: operations["approve_operation_api_operations__operation_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute Operation Endpoint
         * @description Executes an approved operation.
         *     Requires OPERATOR role / operation.execute permission.
         *     Enforces that operation was approved prior to execution.
         */
        post: operations["execute_operation_endpoint_api_operations__operation_id__execute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation
         * @description Get operation status and details (requires operation.view permission).
         */
        get: operations["get_operation_api_operations__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Operation
         * @description Request operation cancellation (requires operation.request permission).
         */
        post: operations["cancel_operation_api_operations__operation_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{operation_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Operation Events
         * @description Retrieve audit and lifecycle events for an operation (requires operation.view permission).
         */
        get: operations["get_operation_events_api_operations__operation_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery-objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recovery Objects
         * @description List sealed recovery objects metadata (requires recovery.view permission, no secret leakage).
         */
        get: operations["list_recovery_objects_api_recovery_objects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recovery-objects/{recovery_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Recovery Object
         * @description Restore a controlled-recoverable object to a validated destination.
         *     Requires authenticated user with recovery.execute permission.
         *     Rejects existing destination files by default unless allow_overwrite=True.
         */
        post: operations["restore_recovery_object_api_recovery_objects__recovery_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Certificate
         * @description Retrieve an issued certificate (requires evidence.view permission, no private key exposure).
         */
        get: operations["get_certificate_api_certificates__certificate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{certificate_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Certificate Endpoint
         * @description Verify certificate authenticity, evidence hash, and Ed25519 signature.
         *     Requires evidence.verify permission.
         *     Reports dimension-level results for explicit security status.
         */
        post: operations["verify_certificate_endpoint_api_certificates__certificate_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Evidence Endpoint
         * @description Verify raw evidence package signature against Ed25519 public key (requires evidence.verify permission).
         */
        post: operations["verify_evidence_endpoint_api_evidence_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CertificateOut */
        CertificateOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /** Evidence Digest */
            evidence_digest: string;
            /** Signing Algorithm */
            signing_algorithm: string;
            /** Key Id */
            key_id?: string | null;
            /** Public Key */
            public_key: string;
            /** Signature */
            signature: string;
            /** Claim */
            claim?: string | null;
            /**
             * Issued At
             * Format: date-time
             */
            issued_at: string;
        };
        /** CertificateVerificationOut */
        CertificateVerificationOut: {
            /** Certificate Id */
            certificate_id: string;
            /**
             * Overall Status
             * @enum {string}
             */
            overall_status: "VALID" | "INVALID" | "INCONCLUSIVE";
            /**
             * Dimensions
             * @description Exactly one result per verification dimension. A PASS on SIGNATURE_VALIDITY does not imply overall certificate validity: only overall_status does. NOT_CHECKED and INCONCLUSIVE are honest absences of evidence and must not be rendered as success.
             */
            dimensions: components["schemas"]["DimensionResultOut"][];
            /** Signature Valid */
            signature_valid?: boolean | null;
            /** Evidence Integrity */
            evidence_integrity?: boolean | null;
            /** Signer Trusted */
            signer_trusted?: boolean | null;
            /** Cannot Prove */
            cannot_prove?: string[];
        };
        /** ConfirmationInput */
        ConfirmationInput: {
            /**
             * Acknowledged Risk
             * @description Must explicitly acknowledge destructive operation risk
             */
            acknowledged_risk: boolean;
        };
        /** CreateOperationRequest */
        CreateOperationRequest: {
            /** Target Id */
            target_id: string;
            /** Mode */
            mode: string;
            /**
             * Policy Id
             * @description Must be an allowlisted backend policy. Currently registered: ERASURE.LOGICAL.SELECTIVE.V1, ERASURE.LOGICAL.TREE.V1, ERASURE.RECOVERABLE.ENCRYPTED.V1. The backend rejects any other identifier; the frontend must not invent policy identifiers.
             * @default ERASURE.LOGICAL.SELECTIVE.V1
             */
            policy_id: string;
            confirmation: components["schemas"]["ConfirmationInput"];
            recovery?: components["schemas"]["RecoveryConfig"] | null;
        };
        /** DimensionResultOut */
        DimensionResultOut: {
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "STRUCTURE" | "VERSION_COMPATIBILITY" | "EVIDENCE_AVAILABILITY" | "EVIDENCE_DIGEST" | "SIGNATURE_VALIDITY" | "PUBLIC_KEY_CONSISTENCY" | "SIGNER_TRUST" | "EVIDENCE_CHAIN_INTEGRITY" | "OPERATION_CONSISTENCY" | "TARGET_CONSISTENCY";
            /**
             * Result
             * @enum {string}
             */
            result: "PASS" | "FAIL" | "NOT_CHECKED" | "INCONCLUSIVE";
            /** Detail */
            detail: string;
            /** Evidence Ref */
            evidence_ref?: string | null;
        };
        /** EvidenceVerificationRequest */
        EvidenceVerificationRequest: {
            /** Evidence */
            evidence: {
                [key: string]: unknown;
            };
            /** Signature */
            signature: string;
            /** Public Key */
            public_key: string;
        };
        /** EvidenceVerificationResult */
        EvidenceVerificationResult: {
            /** Valid */
            valid: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            user: components["schemas"]["UserOut"];
        };
        /** LogoutResponse */
        LogoutResponse: {
            /**
             * Status
             * @default COMPLETED
             */
            status: string;
            /**
             * Message
             * @default Session successfully terminated
             */
            message: string;
        };
        /** OperationEventOut */
        OperationEventOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /** Sequence */
            sequence: number;
            /** Event Type */
            event_type: string;
            /** From State */
            from_state?: string | null;
            /** To State */
            to_state?: string | null;
            /** Payload */
            payload?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OperationOut */
        OperationOut: {
            /** Id */
            id: string;
            /** Target Id */
            target_id: string;
            /** Mode */
            mode: string;
            /**
             * State
             * @description Operation lifecycle state. Authoritative values: CREATED, ANALYZING, PENDING_APPROVAL, READY, ERASING, VERIFYING, RECOVERY_TEST, RESIDUAL_SCAN, RESIDUAL_ANALYSIS, ASSESSING, CERTIFYING, COMPLETED, PARTIAL, FAILED, INCONCLUSIVE, CANCELLED. Terminal states: COMPLETED, PARTIAL, FAILED, INCONCLUSIVE, CANCELLED. Consumers must render PARTIAL and INCONCLUSIVE as distinct outcomes and must never collapse them into success.
             */
            state: string;
            /** Policy Id */
            policy_id?: string | null;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /** Warnings */
            warnings?: string[];
            /** Error */
            error?: {
                [key: string]: unknown;
            } | null;
            /** Actor Id */
            actor_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at?: string | null;
            /** Completed At */
            completed_at?: string | null;
        };
        /** RecoveryConfig */
        RecoveryConfig: {
            /**
             * Retention Seconds
             * @default 86400
             */
            retention_seconds: number | null;
        };
        /** RecoveryObjectOut */
        RecoveryObjectOut: {
            /** Id */
            id: string;
            /** Operation Id */
            operation_id: string;
            /**
             * Status
             * @default SEALED
             */
            status: string;
            /** Original Sha256 */
            original_sha256: string;
            /** Original Size */
            original_size?: number | null;
            /** Created At */
            created_at?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** RestoreRequest */
        RestoreRequest: {
            /** Destination */
            destination: string;
            /**
             * Allow Overwrite
             * @description Explicit consent flag required to overwrite an existing destination file
             * @default false
             */
            allow_overwrite: boolean;
        };
        /** RestoreResponse */
        RestoreResponse: {
            /** Status */
            status: string;
            /** Destination */
            destination: string;
            /** Sha256 */
            sha256: string;
            /** Integrity Verified */
            integrity_verified: boolean;
        };
        /**
         * TargetAnalyzeRequest
         * @description Request to analyze a target.
         */
        TargetAnalyzeRequest: {
            /** Path */
            path: string;
            /**
             * Include Content Analysis
             * @default false
             */
            include_content_analysis: boolean;
        };
        /** TargetOut */
        TargetOut: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Canonical Path */
            canonical_path: string;
            /** Target Type */
            target_type: string;
            /** File Count */
            file_count?: number | null;
            /** Total Size */
            total_size?: number | null;
            /** Sha256 */
            sha256?: string | null;
            /**
             * Discovered At
             * Format: date-time
             */
            discovered_at: string;
        };
        /**
         * TargetProfile
         * @description Profile of analyzed target.
         */
        TargetProfile: {
            /** Id */
            id: string;
            /** Path */
            path: string;
            /** Canonical Path */
            canonical_path?: string | null;
            /** Type */
            type: string;
            /**
             * Size Bytes
             * @default 0
             */
            size_bytes: number;
            /**
             * File Count
             * @default 0
             */
            file_count: number;
            /** Sha256 */
            sha256?: string | null;
            /** Storage Profile */
            storage_profile?: {
                [key: string]: unknown;
            };
            /** Sensitivity */
            sensitivity?: {
                [key: string]: unknown;
            } | null;
            /** Warnings */
            warnings?: string[];
            /** Errors */
            errors?: string[];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Username */
            username: string;
            /** Roles */
            roles?: string[];
            /** Permissions */
            permissions?: string[];
            /**
             * Disabled
             * @default false
             */
            disabled: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Authenticated At */
            last_authenticated_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_profile_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_target_api_targets_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_target_api_targets__target_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                target_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TargetOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_operation_api_operations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOperationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_operation_api_operations__operation_id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    execute_operation_endpoint_api_operations__operation_id__execute_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_api_operations__operation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_operation_api_operations__operation_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_operation_events_api_operations__operation_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recovery_objects_api_recovery_objects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryObjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_recovery_object_api_recovery_objects__recovery_id__restore_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                recovery_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_certificate_api_certificates__certificate_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_certificate_endpoint_api_certificates__certificate_id__verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                certificate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CertificateVerificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_evidence_endpoint_api_evidence_verify_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceVerificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceVerificationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
