import type {
  Operation,
  RecoveryObject,
  ResidualFinding,
  Certificate,
  AuditEvent,
  SystemComponent,
  TargetProfile,
  AiAnalysis,
} from './types'

// A clean mock adapter. In production these shapes come from the OpenAPI
// contract; nothing here fabricates backend security decisions.

export const operations: Operation[] = [
  {
    id: 'OP-2F9A41C7',
    target: 'quarterly-forecast.xlsx',
    targetPath: '/mnt/test-vol/finance/quarterly-forecast.xlsx',
    mode: 'MULTI_PASS',
    policy: 'NIST 800-88 Purge',
    state: 'COMPLETED',
    progress: 100,
    currentStage: 'Certificate issued',
    startedAt: '2026-09-06T09:12:04Z',
    durationMs: 184_000,
    sizeBytes: 19_284_992,
    fileCount: 1,
    assurance: 'VALIDATED',
    warnings: [],
    stages: [
      { id: 'analyze', label: 'Analysis', state: 'done', durationMs: 4200, detail: '1 file, HIGH sensitivity' },
      { id: 'policy', label: 'Policy', state: 'done', durationMs: 300, detail: 'NIST 800-88 Purge' },
      { id: 'execute', label: 'Execution', state: 'done', durationMs: 96_000, detail: '3-pass overwrite + verify' },
      { id: 'verify', label: 'Verification', state: 'done', durationMs: 22_000 },
      { id: 'recovery', label: 'Recovery test', state: 'done', durationMs: 41_000, detail: 'Target not recoverable' },
      { id: 'residual', label: 'Residual scan', state: 'done', durationMs: 16_000, detail: '2 low-risk artifacts' },
      { id: 'assurance', label: 'Assurance', state: 'done', durationMs: 1200, detail: 'Validated in scope' },
      { id: 'certificate', label: 'Certificate', state: 'done', durationMs: 900 },
    ],
  },
  {
    id: 'OP-77B0E312',
    target: 'client-pii-export.csv',
    targetPath: '/mnt/test-vol/exports/client-pii-export.csv',
    mode: 'CRYPTO_ERASE',
    policy: 'Crypto Erase (AES key destruction)',
    state: 'ERASING',
    progress: 46,
    currentStage: 'Key destruction in progress',
    startedAt: '2026-09-06T10:02:47Z',
    sizeBytes: 4_812_004,
    fileCount: 1,
    warnings: ['Snapshot detected on volume — outside erasure scope'],
    stages: [
      { id: 'analyze', label: 'Analysis', state: 'done', durationMs: 3800, detail: 'CRITICAL sensitivity' },
      { id: 'policy', label: 'Policy', state: 'done', durationMs: 250 },
      { id: 'execute', label: 'Execution', state: 'active', detail: 'Destroying wrapping key' },
      { id: 'verify', label: 'Verification', state: 'pending' },
      { id: 'recovery', label: 'Recovery test', state: 'pending' },
      { id: 'residual', label: 'Residual scan', state: 'pending' },
      { id: 'assurance', label: 'Assurance', state: 'pending' },
      { id: 'certificate', label: 'Certificate', state: 'pending' },
    ],
  },
  {
    id: 'OP-1C4D9E80',
    target: 'legacy-backup-04',
    targetPath: '/mnt/test-vol/backups/legacy-backup-04',
    mode: 'SINGLE_PASS',
    policy: 'Single-pass overwrite',
    state: 'INCONCLUSIVE',
    progress: 100,
    currentStage: 'Assessment complete',
    startedAt: '2026-09-06T08:41:19Z',
    durationMs: 121_000,
    sizeBytes: 240_128_512,
    fileCount: 3120,
    assurance: 'INCONCLUSIVE',
    warnings: ['Underlying storage did not confirm physical overwrite (SSD wear-levelling)'],
    stages: [
      { id: 'analyze', label: 'Analysis', state: 'done', durationMs: 8100 },
      { id: 'policy', label: 'Policy', state: 'done', durationMs: 300 },
      { id: 'execute', label: 'Execution', state: 'done', durationMs: 72_000 },
      { id: 'verify', label: 'Verification', state: 'inconclusive', detail: 'Overwrite not physically confirmable' },
      { id: 'recovery', label: 'Recovery test', state: 'done', durationMs: 28_000 },
      { id: 'residual', label: 'Residual scan', state: 'done', durationMs: 12_000, detail: '1 elevated artifact' },
      { id: 'assurance', label: 'Assurance', state: 'inconclusive' },
      { id: 'certificate', label: 'Certificate', state: 'skipped' },
    ],
  },
  {
    id: 'OP-A013FB55',
    target: 'temp-cache-fragment',
    targetPath: '/mnt/test-vol/tmp/temp-cache-fragment',
    mode: 'SINGLE_PASS',
    policy: 'Single-pass overwrite',
    state: 'FAILED',
    progress: 62,
    currentStage: 'Execution halted',
    startedAt: '2026-09-06T07:55:02Z',
    durationMs: 39_000,
    sizeBytes: 1_048_576,
    fileCount: 1,
    warnings: [],
    error: {
      code: 'ERR_DEVICE_BUSY',
      message: 'Target volume became read-only during overwrite. No changes were verified.',
      retryable: true,
      requestId: 'req_8842aa10',
    },
    stages: [
      { id: 'analyze', label: 'Analysis', state: 'done', durationMs: 2100 },
      { id: 'policy', label: 'Policy', state: 'done', durationMs: 200 },
      { id: 'execute', label: 'Execution', state: 'failed', detail: 'Device became read-only' },
      { id: 'verify', label: 'Verification', state: 'skipped' },
      { id: 'recovery', label: 'Recovery test', state: 'skipped' },
      { id: 'residual', label: 'Residual scan', state: 'skipped' },
      { id: 'assurance', label: 'Assurance', state: 'skipped' },
      { id: 'certificate', label: 'Certificate', state: 'skipped' },
    ],
  },
  {
    id: 'OP-5E8221AA',
    target: 'session-tokens.log',
    targetPath: '/mnt/test-vol/var/session-tokens.log',
    mode: 'PURGE',
    policy: 'NIST 800-88 Purge',
    state: 'PARTIAL',
    progress: 100,
    currentStage: 'Partial completion',
    startedAt: '2026-09-05T22:14:40Z',
    durationMs: 156_000,
    sizeBytes: 8_388_608,
    fileCount: 12,
    assurance: 'PARTIALLY_VALIDATED',
    warnings: ['2 of 12 files were locked by another process and skipped'],
    stages: [
      { id: 'analyze', label: 'Analysis', state: 'done', durationMs: 3300 },
      { id: 'policy', label: 'Policy', state: 'done', durationMs: 250 },
      { id: 'execute', label: 'Execution', state: 'done', durationMs: 110_000, detail: '10 of 12 files erased' },
      { id: 'verify', label: 'Verification', state: 'done', durationMs: 22_000 },
      { id: 'recovery', label: 'Recovery test', state: 'done', durationMs: 15_000 },
      { id: 'residual', label: 'Residual scan', state: 'done', durationMs: 5000 },
      { id: 'assurance', label: 'Assurance', state: 'done', detail: 'Partial scope' },
      { id: 'certificate', label: 'Certificate', state: 'done', durationMs: 800 },
    ],
  },
]

export const recoveryObjects: RecoveryObject[] = [
  {
    id: 'RV-9931A0',
    operationId: 'OP-5E8221AA',
    label: 'recoverable-delete/report-draft.docx',
    status: 'SEALED',
    createdAt: '2026-09-06T10:20:00Z',
    expiresAt: '2026-09-13T10:20:00Z',
    originalHash: 'a3f1c9e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d2',
    restoreResult: 'PENDING',
  },
  {
    id: 'RV-77C4E1',
    operationId: 'OP-2F9A41C7',
    label: 'vault/quarterly-forecast.snapshot',
    status: 'DENIED',
    createdAt: '2026-09-06T09:30:00Z',
    expiresAt: '2026-09-08T09:30:00Z',
    originalHash: 'ff02c1aa93bb44dd77ee02c1aa93bb44dd77ee02c1aa93bb44dd77ee02c1aa93',
  },
  {
    id: 'RV-4420BD',
    operationId: 'OP-77B0E312',
    label: 'vault/client-index.bin',
    status: 'AUTHORIZED',
    createdAt: '2026-09-06T08:00:00Z',
    expiresAt: '2026-09-10T08:00:00Z',
    originalHash: 'c1e0b7d24a5f8ff02c1aa93bb44dd77ee02c1aa93bb44dd77ee02c1aa93bb44d',
  },
  {
    id: 'RV-1180FA',
    operationId: 'OP-1C4D9E80',
    label: 'vault/legacy-index-04.bin',
    status: 'RESTORED',
    createdAt: '2026-09-05T20:00:00Z',
    expiresAt: '2026-09-12T20:00:00Z',
    originalHash: '9a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d',
    restoreResult: 'HASH_MATCH',
  },
]

export const residualFindings: ResidualFinding[] = [
  {
    id: 'RS-01',
    operationId: 'OP-2F9A41C7',
    artifact: 'Filesystem journal reference',
    artifactType: 'Metadata',
    similarity: 4,
    sensitivity: 'LOW',
    risk: 'LOW',
    location: 'journal:$LogFile offset 0x2f',
    evidence: 'Filename fragment only; no payload bytes recovered.',
  },
  {
    id: 'RS-02',
    operationId: 'OP-2F9A41C7',
    artifact: 'Thumbnail cache entry',
    artifactType: 'Derived artifact',
    similarity: 9,
    sensitivity: 'LOW',
    risk: 'MINIMAL',
    location: 'cache/thumb.db',
    evidence: 'Low-resolution derived preview; outside erasure scope.',
  },
  {
    id: 'RS-03',
    operationId: 'OP-1C4D9E80',
    artifact: 'Unconfirmed physical remnant',
    artifactType: 'Storage cell',
    similarity: null,
    sensitivity: 'HIGH',
    risk: 'ELEVATED',
    location: 'SSD FTL (not host-addressable)',
    evidence:
      'Wear-levelling prevents confirmation that prior cells were overwritten. Result is inconclusive by design — precision is not estimated.',
  },
]

export const certificates: Certificate[] = [
  {
    id: 'CERT-2F9A41C7',
    operationId: 'OP-2F9A41C7',
    target: 'quarterly-forecast.xlsx',
    mode: 'MULTI_PASS',
    assurance: 'VALIDATED',
    evidenceHash: '7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0b7d24a5f8c1e0',
    signatureState: 'SIGNED',
    verification: 'VALID',
    issuedAt: '2026-09-06T09:15:08Z',
  },
  {
    id: 'CERT-5E8221AA',
    operationId: 'OP-5E8221AA',
    target: 'session-tokens.log',
    mode: 'PURGE',
    assurance: 'PARTIALLY_VALIDATED',
    evidenceHash: '02c1aa93bb44dd77ee02c1aa93bb44dd77ee02c1aa93bb44dd77ee02c1aa93bb',
    signatureState: 'SIGNED',
    verification: 'VALID',
    issuedAt: '2026-09-05T22:17:20Z',
  },
]

export const auditEvents: AuditEvent[] = [
  { id: 'EV-0012', timestamp: '2026-09-06T09:15:08Z', actor: 'a.reyes', action: 'certificate.issue', operationId: 'OP-2F9A41C7', result: 'OK', correlationId: 'corr_2f9a41', eventType: 'CERTIFICATE_ISSUED', hash: '7d24a5f8c1e0', prevHash: '02c1aa93bb44' },
  { id: 'EV-0011', timestamp: '2026-09-06T09:14:03Z', actor: 'system', action: 'assurance.assess', operationId: 'OP-2F9A41C7', result: 'OK', correlationId: 'corr_2f9a41', eventType: 'ASSURANCE_VALIDATED', hash: '02c1aa93bb44', prevHash: '9a5f8c1e0b7d' },
  { id: 'EV-0010', timestamp: '2026-09-06T10:21:40Z', actor: 'k.novak', action: 'recovery.restore', operationId: 'OP-5E8221AA', result: 'DENIED', correlationId: 'corr_5e8221', eventType: 'RESTORE_DENIED', hash: '9a5f8c1e0b7d', prevHash: 'ff02c1aa93bb' },
  { id: 'EV-0009', timestamp: '2026-09-06T07:55:41Z', actor: 'a.reyes', action: 'operation.execute', operationId: 'OP-A013FB55', result: 'FAILED', correlationId: 'corr_a013fb', eventType: 'EXECUTION_FAILED', hash: 'ff02c1aa93bb', prevHash: 'c1e0b7d24a5f' },
  { id: 'EV-0008', timestamp: '2026-09-06T08:41:19Z', actor: 'a.reyes', action: 'operation.create', operationId: 'OP-1C4D9E80', result: 'OK', correlationId: 'corr_1c4d9e', eventType: 'OPERATION_CREATED', hash: 'c1e0b7d24a5f', prevHash: '4a5f8c1e0b7d' },
  { id: 'EV-0007', timestamp: '2026-09-05T20:00:12Z', actor: 'k.novak', action: 'recovery.restore', operationId: 'OP-1C4D9E80', result: 'OK', correlationId: 'corr_1c4d9e', eventType: 'RESTORE_HASH_MATCH', hash: '4a5f8c1e0b7d', prevHash: '000000000000' },
]

export const systemComponents: SystemComponent[] = [
  { id: 'api', name: 'API Gateway', status: 'OPERATIONAL', detail: 'v2.4.1 · US-East', latencyMs: 38 },
  { id: 'backend', name: 'Erasure Backend', status: 'OPERATIONAL', detail: '4 workers online', latencyMs: 12 },
  { id: 'privileged', name: 'Privileged Service', status: 'OPERATIONAL', detail: 'Sealed · attested', latencyMs: 5 },
  { id: 'db', name: 'Evidence Store', status: 'OPERATIONAL', detail: 'Append-only ledger', latencyMs: 21 },
  { id: 'ai', name: 'AI Provider', status: 'DEGRADED', detail: 'Elevated latency', latencyMs: 1840 },
  { id: 'storage', name: 'Test Environment', status: 'OPERATIONAL', detail: '/mnt/test-vol mounted', latencyMs: 3 },
]

// erasure activity: last 14 days (erased vs verified vs failed)
export const erasureActivity = [
  { d: 'Aug 24', erased: 12, verified: 12, failed: 0 },
  { d: 'Aug 25', erased: 18, verified: 17, failed: 1 },
  { d: 'Aug 26', erased: 9, verified: 9, failed: 0 },
  { d: 'Aug 27', erased: 22, verified: 20, failed: 2 },
  { d: 'Aug 28', erased: 15, verified: 15, failed: 0 },
  { d: 'Aug 29', erased: 7, verified: 7, failed: 0 },
  { d: 'Aug 30', erased: 11, verified: 10, failed: 1 },
  { d: 'Aug 31', erased: 26, verified: 25, failed: 1 },
  { d: 'Sep 01', erased: 19, verified: 19, failed: 0 },
  { d: 'Sep 02', erased: 24, verified: 22, failed: 2 },
  { d: 'Sep 03', erased: 16, verified: 16, failed: 0 },
  { d: 'Sep 04', erased: 28, verified: 27, failed: 1 },
  { d: 'Sep 05', erased: 21, verified: 20, failed: 1 },
  { d: 'Sep 06', erased: 9, verified: 8, failed: 1 },
]

export const assuranceDistribution = [
  { key: 'VALIDATED', label: 'Validated', value: 184 },
  { key: 'PARTIALLY_VALIDATED', label: 'Partial', value: 27 },
  { key: 'INCONCLUSIVE', label: 'Inconclusive', value: 11 },
  { key: 'FAILED', label: 'Failed', value: 6 },
]

export const methodDistribution = [
  { label: 'Multi-pass', value: 96 },
  { label: 'Crypto erase', value: 74 },
  { label: 'Purge', value: 41 },
  { label: 'Single-pass', value: 17 },
]

// Demo target used by the erasure workflow (the ERASE → VERIFY → PROVE story).
export const demoTargets: { path: string; profile: TargetProfile; ai: AiAnalysis }[] = [
  {
    path: '/mnt/test-vol/finance/quarterly-forecast.xlsx',
    profile: {
      path: '/mnt/test-vol/finance/quarterly-forecast.xlsx',
      name: 'quarterly-forecast.xlsx',
      filesystem: 'ext4',
      volume: 'test-vol',
      volumeId: 'vol-8f21a0c4',
      sizeBytes: 19_284_992,
      fileCount: 1,
      sha256: '3b1f9a7c2e0d4b8a6f5c3e1d9b7a5c3e1d9b7a5c3e1d9b7a5c3e1d9b7a5c3e1d',
      storageClass: 'NVMe SSD',
      overwriteSupported: true,
      trimEnabled: true,
      snapshotsPresent: false,
      sensitivity: 'HIGH',
      warnings: ['TRIM enabled — physical overwrite is best-effort on this device'],
    },
    ai: {
      classifications: [
        { label: 'Financial projections', matches: 42, confidence: 0.94 },
        { label: 'Named individuals', matches: 6, confidence: 0.81 },
        { label: 'Internal account numbers', matches: 3, confidence: 0.76 },
      ],
      summary:
        'Spreadsheet contains unreleased financial projections and a small number of personal identifiers.',
      recommendedMode: 'MULTI_PASS',
      recommendedPolicy: 'NIST 800-88 Purge',
      rationale:
        'High-sensitivity content on TRIM-enabled media. Multi-pass overwrite with post-erase verification and a recovery test is recommended to establish assurance within the supported scope.',
    },
  },
]

export const currentUser = {
  name: 'A. Reyes',
  handle: 'a.reyes',
  role: 'Erasure Operator',
  clearance: 'Level 3',
}
