"""Generate ``docs/OPENAPI.yaml`` from the running FastAPI application.

Rationale
---------
The hand-maintained contract drifted badly from the implementation: it advertised
ten paths while the application served seventeen, omitted the auth surface that
the backend has implemented and verified for some time, and declared
``bearerFormat: JWT`` when the backend issues opaque session tokens.

This generator makes the contract a *derived artifact*: the application is the
only source of truth, so the document cannot claim an endpoint that does not
exist, nor omit one that does.

Usage::

    python scripts/gen_openapi.py            # write docs/OPENAPI.yaml
    python scripts/gen_openapi.py --check    # fail if the file is stale

The security metadata below is documentation only: it does not alter request
handling. The backend keeps enforcing authentication through its dependencies.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(REPO_ROOT / "src"))

OUTPUT_PATH = REPO_ROOT / "docs" / "OPENAPI.yaml"
# The frontend's capability registry derives "is this in the contract?" from this file instead of
# hand-maintaining a boolean, which is how it drifted into claiming that shipped endpoints were
# absent. One command refreshes both halves of the contract.
FRONTEND_PATHS_MODULE = REPO_ROOT / "frontend" / "src" / "lib" / "api" / "contract-paths.ts"
FRONTEND_POLICIES_MODULE = REPO_ROOT / "frontend" / "src" / "lib" / "api" / "contract-policies.ts"

# Endpoints that must be reachable without a credential.  ``/api/auth/login``
# is what mints the token, so it cannot require one.  ``/api/auth/logout``
# tolerates an absent or already-dead token.  ``/health`` is an unauthenticated
# liveness probe.
UNPROTECTED_PATHS = {
    "/api/auth/login",
    "/api/auth/logout",
    "/health",
}


def authoritative_state_names() -> list[str]:
    """Operation states straight out of the backend state machine."""
    from oblivion.core.state.machine import State

    return [s.name for s in State]


def authoritative_policy_ids() -> list[str]:
    """Allowlisted erasure policy identifiers out of the policy registry."""
    from oblivion.core.policy.engine import POLICY_REGISTRY

    return sorted(POLICY_REGISTRY.keys())


def authoritative_verification_enums() -> dict[str, list[str]]:
    """Certificate verification vocabularies out of the verification module.

    The Pydantic API schemas widen these to plain ``str``, so a purely
    generated contract would lose the enumeration that certificate consumers
    depend on.  Re-injecting them here keeps the contract expressive while still
    deriving every value from code rather than from prose.
    """
    from oblivion.certificate.verification import (
        CheckResult,
        VerificationDimension,
        VerificationStatus,
    )

    return {
        "dimensions": [d.value for d in VerificationDimension],
        "results": [r.value for r in CheckResult],
        "statuses": [s.value for s in VerificationStatus],
    }


def build_spec() -> dict[str, Any]:
    from oblivion.api.app import create_app

    spec: dict[str, Any] = create_app().openapi()

    spec["info"]["title"] = "Oblivion API"
    spec["info"]["description"] = (
        "Backend API for controlled data erasure, recovery, residual analysis, "
        "assurance and certificate verification.\n\n"
        "This document is GENERATED by scripts/gen_openapi.py from the FastAPI "
        "application itself. Do not hand-edit it: edit the routes and schemas, "
        "then regenerate.\n\n"
        "Authentication uses HTTP Bearer with opaque server-side session tokens "
        "(Argon2id password hashing, SHA-256 token digest stored server-side). "
        "These are NOT JWTs. There is no refresh-token endpoint and no cookie "
        "based session; the bearer token is the only credential transport."
    )

    # --- accurate security scheme -------------------------------------------
    components = spec.setdefault("components", {})
    components["securitySchemes"] = {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            # The backend mints secrets.token_urlsafe(32); calling that a JWT
            # would mislead every generated client and every reviewer.
            "bearerFormat": "OpaqueSessionToken",
            "description": (
                "Opaque session token issued by POST /api/auth/login. Send as "
                "'Authorization: Bearer <token>'. The server stores only the "
                "SHA-256 digest and revokes it on logout."
            ),
        }
    }
    spec["security"] = [{"bearerAuth": []}]

    for path, operations in spec.get("paths", {}).items():
        for _verb, operation in operations.items():
            if not isinstance(operation, dict):
                continue
            if path in UNPROTECTED_PATHS:
                operation["security"] = []

    # --- document the real enums, sourced from code -------------------------
    states = authoritative_state_names()
    policies = authoritative_policy_ids()

    schemas = components.setdefault("schemas", {})
    operation_out = schemas.get("OperationOut")
    if operation_out:
        operation_out["properties"]["state"]["description"] = (
            "Operation lifecycle state. Authoritative values: "
            + ", ".join(states)
            + ". Terminal states: COMPLETED, PARTIAL, FAILED, INCONCLUSIVE, "
            "CANCELLED. Consumers must render PARTIAL and INCONCLUSIVE as "
            "distinct outcomes and must never collapse them into success."
        )

    create_request = schemas.get("CreateOperationRequest")
    if create_request and "policy_id" in create_request.get("properties", {}):
        create_request["properties"]["policy_id"]["description"] = (
            "Must be an allowlisted backend policy. Currently registered: "
            + ", ".join(policies)
            + ". The backend rejects any other identifier; the frontend must "
            "not invent policy identifiers."
        )

    # --- restore certificate verification enums -----------------------------
    vocab = authoritative_verification_enums()

    dimension_out = schemas.get("DimensionResultOut")
    if dimension_out:
        props = dimension_out["properties"]
        props["dimension"]["enum"] = vocab["dimensions"]
        props["result"]["enum"] = vocab["results"]
        dimension_out["required"] = ["dimension", "result", "detail"]

    verification_out = schemas.get("CertificateVerificationOut")
    if verification_out:
        vprops = verification_out["properties"]
        vprops["overall_status"]["enum"] = vocab["statuses"]
        dims = vprops["dimensions"]
        dims["minItems"] = len(vocab["dimensions"])
        dims["description"] = (
            "Exactly one result per verification dimension. A PASS on "
            "SIGNATURE_VALIDITY does not imply overall certificate validity: "
            "only overall_status does. NOT_CHECKED and INCONCLUSIVE are "
            "honest absences of evidence and must not be rendered as success."
        )

    return spec


def authoritative_policies() -> list[dict[str, object]]:
    """The allowlisted erasure policies, straight from the backend registry."""
    from oblivion.core.policy.engine import POLICY_REGISTRY

    return [
        {
            "policy_id": p.policy_id,
            "name": p.name,
            "allowed_modes": sorted(p.allowed_modes),
            "allowed_target_types": sorted(p.allowed_target_types),
            "requires_approval": p.requires_approval,
            "description": p.description,
        }
        for p in sorted(POLICY_REGISTRY.values(), key=lambda x: x.policy_id)
    ]


def render_policies_module() -> str:
    """Emit the allowlisted policies so the workflow cannot offer a policy the backend rejects."""
    import json

    payload = json.dumps(authoritative_policies(), indent=2)
    return (
        "// GENERATED FILE - DO NOT EDIT.\n"
        "// Written by scripts/gen_openapi.py from oblivion.core.policy.engine.POLICY_REGISTRY.\n"
        "// Regenerate with: python scripts/gen_openapi.py\n"
        "//\n"
        "// The backend validates policy_id against this allowlist and rejects anything else, and it\n"
        "// also enforces mode and target-type compatibility. Offering a policy the registry does not\n"
        "// contain would produce a 400 that reads like an operator mistake.\n"
        "\n"
        "export interface AllowlistedPolicy {\n"
        "  readonly policy_id: string\n"
        "  readonly name: string\n"
        "  readonly allowed_modes: readonly string[]\n"
        "  readonly allowed_target_types: readonly string[]\n"
        "  readonly requires_approval: boolean\n"
        "  readonly description: string\n"
        "}\n"
        "\n"
        "export const ALLOWLISTED_POLICIES: readonly AllowlistedPolicy[] = "
        + payload
        + " as const\n"
        "\n"
        "/** Policies whose allowed modes include `mode`. */\n"
        "export function policiesForMode(mode: string): readonly AllowlistedPolicy[] {\n"
        "  return ALLOWLISTED_POLICIES.filter((p) => p.allowed_modes.includes(mode))\n"
        "}\n"
    )


def render(spec: dict[str, Any]) -> str:
    header = (
        "# GENERATED FILE - DO NOT EDIT.\n"
        "# Produced by scripts/gen_openapi.py from the FastAPI application in\n"
        "# src/oblivion/api. Regenerate with: python scripts/gen_openapi.py\n"
        "# Verify freshness with:      python scripts/gen_openapi.py --check\n"
    )
    body = yaml.safe_dump(spec, sort_keys=False, allow_unicode=True, width=110)
    return header + body


def render_contract_paths(spec: dict[str, Any]) -> str:
    """Emit the contract's operations as a TypeScript module the frontend can assert against."""
    entries: list[str] = []
    for path, operations in spec.get("paths", {}).items():
        for verb, operation in operations.items():
            if not isinstance(operation, dict):
                continue
            entries.append(f'  \'{verb.upper()} {path}\',')
    entries.sort()
    return (
        "// GENERATED FILE - DO NOT EDIT.\n"
        "// Written by scripts/gen_openapi.py from docs/OPENAPI.yaml, which is itself generated\n"
        "// from the FastAPI application. Regenerate with: python scripts/gen_openapi.py\n"
        "//\n"
        "// Every operation the backend actually serves. The frontend capability registry consults\n"
        "// this instead of hand-maintaining an `inContract` boolean, so a capability can never\n"
        "// claim to be contracted when the application does not route it - or be marked absent\n"
        "// while the application already serves it.\n"
        "\n"
        "/** Format: `\"<VERB> <path>\"`, with path parameters left as `{name}`. */\n"
        "export const CONTRACT_OPERATIONS: readonly string[] = [\n"
        + "\n".join(entries)
        + "\n] as const\n"
        "\n"
        "const LOOKUP: ReadonlySet<string> = new Set(CONTRACT_OPERATIONS)\n"
        "\n"
        "/** True when the contract publishes this exact verb+path operation. */\n"
        "export function isContractOperation(method: string, path: string): boolean {\n"
        "  return LOOKUP.has(`${method.toUpperCase()} ${path}`)\n"
        "}\n"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/OPENAPI.yaml is not what the app produces",
    )
    args = parser.parse_args(argv)

    spec = build_spec()
    rendered = render(spec)
    paths_module = render_contract_paths(spec)
    policies_module = render_policies_module()

    def current_text(path: Path) -> str:
        return path.read_text(encoding="utf-8") if path.exists() else ""

    if args.check:
        if (
            current_text(OUTPUT_PATH) != rendered
            or current_text(FRONTEND_PATHS_MODULE) != paths_module
            or current_text(FRONTEND_POLICIES_MODULE) != policies_module
        ):
            print(
                "STALE: docs/OPENAPI.yaml or a generated frontend module does not match the "
                "application.\n       run: python scripts/gen_openapi.py",
                file=sys.stderr,
            )
            return 1
        print(
            f"OK: docs/OPENAPI.yaml matches the running application "
            f"({len(spec['paths'])} paths)"
        )
        return 0

    OUTPUT_PATH.write_text(rendered, encoding="utf-8", newline="\n")
    for destination, content in (
        (FRONTEND_PATHS_MODULE, paths_module),
        (FRONTEND_POLICIES_MODULE, policies_module),
    ):
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
    print(
        f"wrote {OUTPUT_PATH} ({len(spec['paths'])} paths), "
        f"{FRONTEND_PATHS_MODULE.name}, {FRONTEND_POLICIES_MODULE.name}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

